export const SET_USER_IMAGE = 'SET_USER_IMAGE';
export const SET_REGISTER_DATA = 'SET_REGISTER_DATA';
export const SET_ADDRESS_DATA = 'SET_ADDRESS_DATA';
export const SET_GYM_GIFS = 'SET_GYM_GIFS';
export const SET_BRAZILIAN_STATES = 'SET_BRAZILIAN_STATES';
